version: '3'
services:
  react-app:
    build:
      context: ./react-client
      dockerfile: Dockerfile
    ports:
      - 80:80

  express-server:
    build:
      context: ./express-server
      dockerfile: Dockerfile
    ports:
      - 5000:5000
