name: Build and Push Docker Images
on:
  push:
    branches:
      - main

env:
  DOCKER_REGISTRY: https://hub.docker.com/
  DOCKER_COMPOSE_FILE: Express-React-Docker/docker-compose.yml
  DOCKER_IMAGE_NAME: seetharamkoya/express-reactor-docker:v1.1.0
  DOCKER_IMAGE_TAG: latest

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Log in to Docker Hub
        run: echo "${DOCKER_HUB_PASSWORD}" | docker login -u "${DOCKER_HUB_USERNAME}" --password-stdin https://index.docker.io/v1/
        
      - name: Build and Push Docker Images
        run: |
          docker compose build
          docker compose push
