name: Build and Push Docker Images
on:
  push:
    branches:
      - main

env:
  DOCKER_REGISTRY: https://hub.docker.com/
  DOCKER_COMPOSE_FILE: Express-React-Docker/docker-compose.yml
  DOCKER_IMAGE_NAME: seetharamkoya/express-react-docker
  DOCKER_IMAGE_TAG: latest

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD}}
        
      - name: Build and Push Docker Images
        run: |
          docker compose build
          docker compose push
