name: Build and Push Docker Images
on:
  push:
    branches:
      - main

env:
  DOCKER_REGISTRY: https://hub.docker.com/
  DOCKER_COMPOSE_FILE: ./docker-compose.yml
  IMAGE_NAME: ${{ github.repository }}
  

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Lowercase the repo name
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN}}
      
      - name: Build and Push Docker Image express-server
        run: |
            cd express-server
            docker build -t seetharamkoya/express-react-docke:latest .
            docker push seetharamkoya/express-react-docke:latest
  
      - name: Build and Push Docker Image react-client
        run: |
            cd react-client
            docker build -t seetharamkoya/express-react-docke:latest .
            docker push seetharamkoya/express-react-docke:latest