name: Build and Push Docker Images-react
on:
  workflow_dispatch:

env:
  DOCKER_REGISTRY: https://hub.docker.com/
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/react-docker
  

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Lowercase the repo name
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Docker Image Version
        id: version
        run: |
          if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
            echo "::set-output name=version::${GITHUB_REF#refs/heads/}-${GITHUB_SHA:0:7}"
          else
            echo "::set-output name=version::latest"
          fi

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN}}

      - name: Build and Push Docker Image
        run: |
          cd react-client
          docker build -t $IMAGE_NAME .
          docker tag $IMAGE_NAME:latest $IMAGE_NAME:${{ steps.version.outputs.version }}
          docker push $IMAGE_NAME:latest 
          docker push $IMAGE_NAME:${{ steps.version.outputs.version }}
  

  deploy-react:
    needs: build-and-push 
    runs-on: ubuntu-latest     
    steps:
      - name: Deploy to EC2 Instance
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST}}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}   
      - name: deplyingimages
        run: |
          sudo apt-get update -y
          sudo apt-get install docker.io -y
          sudo systemctl start docker
          sudo usermod -a -G docker ec2-user
          docker pull ${IMAGE_NAME}:latest
          docker ps
          docker run -d -p 80:80 --name ${IMAGE_NAME}:latest
        
