name: Build and Push Docker Images-react
on:
  push:
    paths:
      - react-client/**

env:
  DOCKER_REGISTRY: https://hub.docker.com/
  IMAGE_NAME: ${{ github.repository }}
  

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Lowercase the repo name
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Docker Image Version
        id: version
        run: |
          if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
            echo "::set-output name=version::${GITHUB_REF#refs/heads/}-${GITHUB_SHA:0:7}"
          else
            echo "::set-output name=version::latest"
          fi

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN}}

      - name: Build and Push Docker Image
        run: |
          cd react-client
          docker build -t seetharamkoya/react-docker:${{ steps.version.outputs.version }} .
          docker push seetharamkoya/react-docker:${{ steps.version.outputs.version }}