name: Build and Push Docker Images
on:
  push:
    branches:
      - main

env:
  DOCKER_REGISTRY: https://hub.docker.com/
  DOCKER_COMPOSE_FILE: ./docker-compose.yml
  IMAGE_NAME: ${{ github.repository }}
  

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Lowercase the repo name
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Docker Image Version
        id: version
        run: |
          if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
            echo "::set-output name=version::latest"
          else
            echo "::set-output name=version::${GITHUB_REF#refs/heads/}-${GITHUB_SHA:0:7}"
          fi
      

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN}}
      
      - name: Build and Push Docker Image express-server
        run: |
            cd express-server
            docker build -t seetharamkoya/express-docker:${{ steps.version.outputs.version }} .
            docker push seetharamkoya/express-react-docker:${{ steps.version.outputs.version }}
  
      - name: Build and Push Docker Image react-client
        run: |
            cd react-client
            docker build -t seetharamkoya/react-docker:${{ steps.version.outputs.version }} .
            docker push seetharamkoya/react-docker:${{ steps.version.outputs.version }}