name: Deploy to EC2
on:
    push:
      branches:
        - main

  

jobs:
    deploy-react:
        runs-on: ubuntu-latest     
        steps:
          - name: Checkout Repository
            uses: actions/checkout@v2

          - name: Deploy to EC2 Instance
            uses: easingthemes/ssh-deploy@main
            with:
              SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
              REMOTE_HOST: ${{ secrets.REMOTE_HOST}}
              REMOTE_USER: ${{ secrets.REMOTE_USER }}   
          - name: deploy images
            run: |
                sudo curl -L https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
                sudo chmod +x /usr/local/bin/docker-compose
                sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
                docker-compose version
                docker-compose -d

    
          
