name: CI/CD
on:
 workflow_dispatch:

jobs:
 deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Deploy to EC2 Instance
      uses: easingthemes/ssh-deploy@main
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        REMOTE_HOST: ${{ secrets.REMOTE_HOST}}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        run: |
            sudo yum update -y
            sudo amazon-linux-extras install docker -y
            sudo service docker start
            sudo usermod -a -G docker ec2-user |
            docker-compose up -d
    