name: Deploy to EC2

on:
    workflow_dispatch:
  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy Docker image
        run: |
          ssh -o StrictHostKeyChecking=no <username>@<hostname> << 'EOF'
            # Pull the latest Docker image
            docker pull seetharamkoya/react-docker
            
            # Run the new container
            docker run -d --name react-container -p 80:80 seetharamkoya/react-docker
          EOF
